_target_: src.models.cifar10_diffusion_model.CIFAR10DiffusionModule

lr: 2e-4

model:
  _target_: src.models.modules.diffusion.Diffusion
  image_size: 32
  in_channels: 3
  out_channels: 3
  timesteps: 1000
